# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/design1_direct/design1_direct.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct || ORIG_REF_NAME==design1_direct} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_inference_bram_inter_0_0/design1_direct_inference_bram_inter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_inference_bram_inter_0_0 || ORIG_REF_NAME==design1_direct_inference_bram_inter_0_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_axi_bram_ctrl_0_0/design1_direct_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design1_direct_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_axi_gpio_0_0/design1_direct_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_axi_gpio_0_0 || ORIG_REF_NAME==design1_direct_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_axi_gpio_1_0/design1_direct_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_axi_gpio_1_0 || ORIG_REF_NAME==design1_direct_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_axi_smc_0/design1_direct_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_axi_smc_0 || ORIG_REF_NAME==design1_direct_axi_smc_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_blk_mem_gen_0_0/design1_direct_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_blk_mem_gen_0_0 || ORIG_REF_NAME==design1_direct_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_processing_system7_0_0/design1_direct_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_processing_system7_0_0 || ORIG_REF_NAME==design1_direct_processing_system7_0_0} -quiet] -quiet

# IP: bd/design1_direct/ip/design1_direct_rst_ps7_0_50M_0/design1_direct_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design1_direct_rst_ps7_0_50M_0 || ORIG_REF_NAME==design1_direct_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: e:/TsetlinMachine/tsetlin_multiple_images_inference.gen/sources_1/bd/design1_direct/design1_direct_ooc.xdc
