set_property PACKAGE_PIN M15 [get_ports start_0]
set_property PACKAGE_PIN H17 [get_ports start_compute_0]

set_property IOSTANDARD LVCMOS18 [get_ports start_0]
set_property IOSTANDARD LVCMOS18 [get_ports start_compute_0]

set_property PACKAGE_PIN U14 [get_ports result_ready_0]
set_property IOSTANDARD LVCMOS18 [get_ports result_ready_0]

set_property PACKAGE_PIN T22 [get_ports {led_0[6]}]
set_property PACKAGE_PIN T21 [get_ports {led_0[5]}]
set_property PACKAGE_PIN U22 [get_ports {led_0[4]}]
set_property PACKAGE_PIN U21 [get_ports {led_0[3]}]
set_property PACKAGE_PIN V22 [get_ports {led_0[2]}]
set_property PACKAGE_PIN W22 [get_ports {led_0[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_0[0]}]
