# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/tsetlin_multiple_images_inference/tsetlin_multiple_images_inference.srcs/sources_1/bd/design1_direct/ip/design1_direct_processing_system7_0_0/design1_direct_processing_system7_0_0.xci
# IP: The module: 'design1_direct_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tsetlin_multiple_images_inference/tsetlin_multiple_images_inference.gen/sources_1/bd/design1_direct/ip/design1_direct_processing_system7_0_0/design1_direct_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_direct_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/tsetlin_multiple_images_inference/tsetlin_multiple_images_inference.srcs/sources_1/bd/design1_direct/ip/design1_direct_processing_system7_0_0/design1_direct_processing_system7_0_0.xci
# IP: The module: 'design1_direct_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tsetlin_multiple_images_inference/tsetlin_multiple_images_inference.gen/sources_1/bd/design1_direct/ip/design1_direct_processing_system7_0_0/design1_direct_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design1_direct_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
